# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
a = np.random.random((3,2,5))

In [ ]:
# Method 2
from numpy import random
a = random.rand(2, 3, 5)

In [ ]:
# Method 3
a = np.arange(30).reshape(2,3,5)

#### 4. Print *a*.


In [11]:
# your code here
a

array([[[0.65967149, 0.05012118, 0.84995494, 0.49386928, 0.50650403],
        [0.51269866, 0.70453199, 0.0948251 , 0.94681566, 0.90932377]],

       [[0.03148424, 0.73107168, 0.17739342, 0.34758518, 0.25551017],
        [0.64421598, 0.18601403, 0.02930919, 0.50971733, 0.91468407]],

       [[0.62391239, 0.26833556, 0.77487822, 0.82269807, 0.7636124 ],
        [0.66913696, 0.20592168, 0.6828023 , 0.84736698, 0.18097778]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [5]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [6]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [7]:
# your code here
a.size == b.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
no. Because they don't have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [8]:
# your code here
c = np.transpose(b)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = sum(a,c)
d


array([[[2.31506812, 2.04952842, 2.80222658, 2.66415252, 2.52562661],
        [2.82605159, 2.0964677 , 1.80693659, 3.30389998, 3.00498562]],

       [[2.31506812, 2.04952842, 2.80222658, 2.66415252, 2.52562661],
        [2.82605159, 2.0964677 , 1.80693659, 3.30389998, 3.00498562]],

       [[2.31506812, 2.04952842, 2.80222658, 2.66415252, 2.52562661],
        [2.82605159, 2.0964677 , 1.80693659, 3.30389998, 3.00498562]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(d)

[[[2.31506812 2.04952842 2.80222658 2.66415252 2.52562661]
  [2.82605159 2.0964677  1.80693659 3.30389998 3.00498562]]

 [[2.31506812 2.04952842 2.80222658 2.66415252 2.52562661]
  [2.82605159 2.0964677  1.80693659 3.30389998 3.00498562]]

 [[2.31506812 2.04952842 2.80222658 2.66415252 2.52562661]
  [2.82605159 2.0964677  1.80693659 3.30389998 3.00498562]]]


In [ ]:
a

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a*c
e

array([[[0.65967149, 0.05012118, 0.84995494, 0.49386928, 0.50650403],
        [0.51269866, 0.70453199, 0.0948251 , 0.94681566, 0.90932377]],

       [[0.03148424, 0.73107168, 0.17739342, 0.34758518, 0.25551017],
        [0.64421598, 0.18601403, 0.02930919, 0.50971733, 0.91468407]],

       [[0.62391239, 0.26833556, 0.77487822, 0.82269807, 0.7636124 ],
        [0.66913696, 0.20592168, 0.6828023 , 0.84736698, 0.18097778]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
yes, because c contains only 1 inside

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [15]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
d_max

3.303899979168642

In [16]:
d_min

1.8069365869610023

In [17]:
d_mean

2.539494372736452

In [28]:
d.shape

(3, 2, 5)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [31]:
# your code here
f = np.empty(d.shape)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [46]:
# your code here
index = (a, b, c)
for a in range(0, d.shape[0]):
    for b in range(0, d.shape[1]):
        for c in range(0, d.shape[2]):
            if d[index] > d_min and d[index] < d_mean:
                    f[index] = 25
            elif d[index] > d_mean and d[index] < d_max:
                    f[index] = 75
            elif d[index] == d_mean:
                    f[index] = 50
            elif d[index] == d_min:
                    f[index] = 0
            elif d[index] == d_max:
                    f[index] = 100
f


array([[[ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,   0., 100.,  75.]],

       [[ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,   0., 100.,  75.]],

       [[ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,   0., 100.,  75.]]])

In [55]:
f =[]
for x in np.nditer(d):
    if x > d_min and x < d_mean:
            f  += [25]
    elif x > d_mean and x < d_max:
            f  += [75]
    elif x == d_mean:
            f  += [50]
    elif x == d_min:
            f  += [0]
    elif x == d_max:
            f  += [100]
f = np.reshape(f, d.shape)
f

array([[[ 25,  25,  25,  25,  25],
        [ 25,  75,  75,  75,  75]],

       [[ 75,  75,  25,  25,  25],
        [ 75,  75,  75,  25,  25]],

       [[ 25,   0,   0,   0, 100],
        [100, 100,  75,  75,  75]]])

# 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [47]:
# your code here
f

array([[[ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,   0., 100.,  75.]],

       [[ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,   0., 100.,  75.]],

       [[ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,   0., 100.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here
f =[]
for x in np.nditer(d):
    if x > d_min and x < d_mean:
            f  += ['D']
    elif x > d_mean and x < d_max:
            f  += ['B']
    elif x == d_mean:
            f  += ['C']
    elif x == d_min:
            f  += ['E']
    elif x == d_max:
            f  += ['A']
f = np.reshape(f, d.shape)
f

array([[['D', 'D', 'D', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'B']],

       [['B', 'B', 'D', 'D', 'D'],
        ['B', 'B', 'B', 'D', 'D']],

       [['D', 'E', 'E', 'E', 'A'],
        ['A', 'A', 'B', 'B', 'B']]], dtype='<U1')